Models/ErrorViewModel.cs
using System;

namespace clearskylogic.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Property.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace clearskylogic.Models
{
    public class Property
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public decimal price { get; set; }
        public string Bedroom { get; set; }
        public string Image { get; set; }
    }
}

Controllers/GetPropertiesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using clearskylogic.Data;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System;
using System.Net.Mail;

namespace clearskylogicproperties1.Controllers
{
    public class GetPropertiesController : Controller
    {
        //PropertiesController propertiesController;
        private readonly clearskylogicContext _context;

        public GetPropertiesController(clearskylogicContext context)
        {
            _context = context;
        }

        //
        // GET: /GetPropertiesController
        public async Task<IActionResult> Index()
        {
            return View(await _context.Property.ToListAsync());
        }

        // GET: PropertyList/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @property = await _context.Property
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@property == null)
            {
                return NotFound();
            }

            return View(@property);
        }

        //
        // GET: /GetProperties/SendEnquiry
        public IActionResult SendEnquiry()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using clearskylogic.Models;

namespace clearskylogic.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PropertiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using clearskylogic.Data;
using clearskylogic.Models;
using clearskylogic.Services;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace clearskylogic.Controllers
{
    public class PropertiesController : Controller
    {
        private readonly clearskylogicContext _context;
        private readonly UploadService _uploadService;

        public PropertiesController(clearskylogicContext context, UploadService uploadService)
        {
            _context = context;

            _uploadService = uploadService;
        }

        // GET: Properties
        public async Task<IActionResult> Index()
        {
            return View(await _context.Property.ToListAsync());
        }

        // GET: Properties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @property = await _context.Property
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@property == null)
            {
                return NotFound();
            }

            return View(@property);
        }

        // GET: Properties/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Properties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Address,Description,price,Bedroom")] Property @property, IFormFile Image)
        {
            @property.Image = _uploadService.UploadFile(Image);

            if (ModelState.IsValid)
            {
                _context.Add(@property);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@property);
        }

        // GET: Properties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @property = await _context.Property.FindAsync(id);
            if (@property == null)
            {
                return NotFound();
            }
            return View(@property);
        }

        // POST: Properties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Address,Description,price,Bedroom")] Property @property, IFormFile Image)
        {
            @property.Image = _uploadService.UploadFile(Image);

            if (id != @property.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@property);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PropertyExists(@property.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@property);
        }

        // GET: Properties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @property = await _context.Property
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@property == null)
            {
                return NotFound();
            }

            return View(@property);
        }

        // POST: Properties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @property = await _context.Property.FindAsync(id);
            _context.Property.Remove(@property);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PropertyExists(int id)
        {
            return _context.Property.Any(e => e.Id == id);
        }
    }
}

Views/GetProperties/Details.cshtml
@model clearskylogic.Models.Property
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

@{
    ViewData["Title"] = "Details";
}

<h1>@Html.DisplayFor(model => model.Address)</h1>

<div>
    <hr />
    <div class="row">
        <div class="col-sm-6">
            <h5>@Html.DisplayNameFor(model => model.Description)</h5>
            <div>
                @Html.DisplayFor(model => model.Description)
            </div>
            <h5>@Html.DisplayNameFor(model => model.price)</h5>
            <div>
                £@Html.DisplayFor(model => model.price)
            </div>
        </div>
        <div class="col-6">
            <div style="max-height: 500px; max-width: 500px;">
                <img src="/@Html.DisplayFor(model => model.Image)" class="img-thumbnail h-100 w-100" />
            </div>
        </div>
    </div>
</div>
@if (SignInManager.IsSignedIn(User))
{
    <form asp-action="SendEnquiry">
        <div class="form-group">
            <label for="enquiryNotes"><h6>Enquire about this property</h6></label>
            <textarea name="enquiryNotes" class="form-control rounded-0" id="enquiryNotes" rows="10"></textarea>
            <button type="submit" class="btn btn-info">Send</button>
        </div>
    </form>
}
    <div>
        <a asp-action="Index">Back to List</a>
    </div>

Views/GetProperties/Index.cshtml
@model IEnumerable<clearskylogic.Models.Property>

@{
    ViewData["Title"] = "Property List";
}

<div class="text-center">
    <h1 class="display-4">Available Properties</h1>
    <div class="container">
        @foreach (var item in Model)
        {
            <div class="row">
                <div class="col-4">
                    <div style="max-height: 500px; max-width: 500px;">
                        <img src="@Html.DisplayFor(modelItem => item.Image)" class="img-thumbnail h-100 w-100" />
                    </div>
                </div>

                <div class="col-8">
                    <div><a asp-action="Details" asp-route-id="@item.Id"><h4>£@Html.DisplayFor(modelItem => item.price)</h4></a></div>
                    <div><h6>@Html.DisplayFor(modelItem => item.Address) Address</h6></div>
                    <div><h6>@Html.DisplayFor(modelItem => item.Bedroom) Bedrooms</h6></div>
                    <div><h7>@Html.DisplayFor(modelItem => item.Description)</h7></div>
                </div>
            </div>
        }
    </div>
</div>

Views/GetProperties/SendEnquiry.cshtml
@{
    ViewData["Title"] = "Enquiry Sent";
}

<div class="text-center">
    <h1 class="display-4">Enquiry Sent</h1>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Clear Sky Logic Properties</h1>
    <a class="btn btn-secondary btn-lg" asp-controller="GetProperties" asp-action="Index">Show Available Properties</a>
</div>

Views/Properties/Create.cshtml
@model clearskylogic.Models.Property

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Property</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bedroom" class="control-label">How Many Bedrooms?</label>
                <input asp-for="Bedroom" class="form-control" />
                <span asp-validation-for="Bedroom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label">Upload Photo of Property</label>
                <input asp-for="Image" type="file" name="Image" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Properties/Delete.cshtml
@model clearskylogic.Models.Property

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Property</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bedroom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bedroom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Properties/Details.cshtml
@model clearskylogic.Models.Property

@{
    ViewData["Title"] = "Details";
}

<h1>@Html.DisplayFor(model => model.Address)</h1>

<div>
    <hr />
    <div class="row">
        <div class="col-sm-6">
            <h5>@Html.DisplayNameFor(model => model.Description)</h5>
    <div>
        @Html.DisplayFor(model => model.Description)
    </div>
    <h5>@Html.DisplayNameFor(model => model.price)</h5>
    <div>
        £@Html.DisplayFor(model => model.price)
    </div>
</div>
        <div class="col-6">
            <div style="max-height: 500px; max-width: 500px;">
                <img src="/@Html.DisplayFor(model => model.Image)" class="img-thumbnail h-100 w-100" />
            </div>
        </div>
    </div>
    <div>
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>

Views/Properties/Edit.cshtml
@model clearskylogic.Models.Property

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Property</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bedroom" class="control-label"></label>
                <input asp-for="Bedroom" class="form-control" />
                <span asp-validation-for="Bedroom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label">Upload Photo of Property</label>
                <input asp-for="Image" type="file" name="Image" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Properties/Index.cshtml
@model IEnumerable<clearskylogic.Models.Property>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bedroom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bedroom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Clear Sky Logic</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @if (SignInManager.IsSignedIn(User)) { 
                        <ul class="navbar-nav justify-content-end">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Properties" asp-action="Index">Admin</a>
                            </li>
                        </ul>
                     }
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GetProperties" asp-action="Index">Property List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>